package com.kolyapetrov.telegram_bot.util.enums;

public enum UserState {
    MAIN,
    ENTER_PHOTOS,
    ENTER_DESCRIPTION_OF_AD,
    ENTER_PRICE,
    ENTER_ADDRESS,
    EDIT_AD,
    ENTER_LOCATION_CORDS,
    ENTER_TITLE_OF_AD,
    ENTER_CITY_FOR_FILTER,
    ENTER_LOWER_PRICE_FOR_FILTER,
    ENTER_UPPER_PRICE_FOR_FILTER,
    ENTER_LOWER_DATE_FOR_FILTER,
    ENTER_UPPER_DATE_FOR_FILTER;
}